# Generated by Django 5.2.6 on 2025-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.CharField(unique=True)),
                ('name_prefix', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=100, verbose_name='ชื่อวิชา')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='ชื่อผู้สอน')),
            ],
        ),
    ]
